spring:
  profiles:
    active: devclient
  jpa:
    hibernate:
        ddl-auto: none
    #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        session_factory:
          interceptor: pe.gob.osce.rnp.seg.interceptor.EntityInterceptorImpl
        jdbc:
          batch_size: 400
          batch_versioned_data: true
        proc:
          param_null_passing: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html
  servlet:
    multipart:
      max-request-size: 1MB
      max-file-size: 2MB